from enum import Enum


class BrowserState(Enum):

    UNKNOWN = "UNKNOWN"

    PAGE_LOADING = "PAGE_LOADING"

    GOOGLE_HOME = "GOOGLE_HOME"

    SEARCH_RESULTS = "SEARCH_RESULTS"

    SEARCH_EMPTY = "SEARCH_EMPTY"

    LOGIN_PAGE = "LOGIN_PAGE"

    LOGIN_REQUIRED = "LOGIN_REQUIRED"

    CAPTCHA = "CAPTCHA"

    ERROR_PAGE = "ERROR_PAGE"

    YOUTUBE_HOME = "YOUTUBE_HOME"

    CHATGPT_HOME = "CHATGPT_HOME"

    CHATGPT_RESPONDING = "CHATGPT_RESPONDING"

    CHATGPT_FINISHED = "CHATGPT_FINISHED"